### ISSUE TITLE
jQuery loading

### ISSUE THREAD

**Issue by nvwieren** [mendix/Bootstrap-RTE#14]
Why is this widget loading jQuery in a different fashion than other widgets created by Mendix - with define and var $ = _jQuery.noConflict(true);

The currently used solution is conflicting/not working in our application.

**Comment by nvwieren** [comment]
Hi Jelte,
Is this recognised as an issue and if so, do you have any idea on a fix/refactoring schedule?
Thanks,
Nick

**Comment by JelteMX** [comment]
I think I have fixed this bug today. Would you be so kind to test this version: https://github.com/mendix/Bootstrap-RTE/raw/master/dist/BootstrapRTE.mpk?

**Comment by nvwieren** [comment]
Issue is resolved, thanks! Will you publish a new version to the appstore?

**Comment by JelteMX** [comment]
This version has been published to the AppStore recently (version 3.1.0) :-)
