### ISSUE TITLE
ShowOnFocus breaks toolbar on IE11

### ISSUE THREAD

**Issue by nvwieren** [mendix/Bootstrap-RTE#15]
If you open the test project from this widget in IE11 and enable the option `Show bar on focus`, once you click the inputfield the toolbar is shown. Then when you click (most) of the toolbar buttons the toolbar closes and doesn't return until you refresh the screen.

Seems the toolbar is placed above the widget domnode (this.domnode) once you click any of the toolbar icons which breaks the lookup _inFocus logic on the domnode children to determine focus.

**Comment by JelteMX** [comment]
Traced this not to the Show bar on focus, but the library itself. I'll see if there is a stable fork of the library that works with IE11, as the current one is stale

**Comment by JelteMX** [comment]
Version [3.2.0](https://github.com/mendix/Bootstrap-RTE/releases/tag/v3.2.0) should fix this (also available in the AppStore). Could you test this version and send feedback?
