### ISSUE TITLE
Indent/Outdent breaks page in IE

### ISSUE THREAD

**Issue by jeroen-huizer-conclusion** [mendix/Bootstrap-RTE#19]
Using the indent or outdent buttons will 'break' the widget in IE 11.
I am using the BootstrapRTE on a simple page (no other widgets / inputs) in an otherwise empty project.

A little debugging leads to the document.execCommand call causing the problem.
When triggering that function directly through the console, the problem occurs as well.

Any idea what could cause this?

Regards,
Jeroen Huizer

![image](https://cloud.githubusercontent.com/assets/21953339/22105676/7ae094d6-de45-11e6-86ca-c2ae2bad099b.png)

![image](https://cloud.githubusercontent.com/assets/21953339/22105682/80ae2176-de45-11e6-9c0d-16325ff40880.png)

**Comment by jeroen-huizer-conclusion** [comment]
Additional finding, after adjusting the widget to insert the _inputfield node in the DOM outside the parentNode (while keeping the toolbar inside) everything works fine. 
When wrapping that inside another widget (groupbox specifically), the problem occurs again.

**Comment by JelteMX** [comment]
Version [3.2.0](https://github.com/mendix/Bootstrap-RTE/releases/tag/v3.2.0) should fix this (also available in the AppStore). Could you test this version and send feedback?

**Comment by jeroen-huizer-conclusion** [comment]
Version 3.2.0 solved the problem. Thanks!

**Comment by JelteMX** [comment]
Great to hear, thanks for the feedback!
