### ISSUE TITLE
Can't select text in IE

### ISSUE THREAD

**Issue by irenadzambo** [mendix/Bootstrap-RTE#22]
I can't select the input of the widget when working in IE. Internet Explorer is the main browser used by my client and they need to copy-paste a lot as part of their work process. It would be great if this issue could be fixed.

**Comment by jeroen-huizer-conclusion** [comment]
This is caused by the clear formatting toolbar button, the associated command (html) is not supported by IE (or any other).
I submitted a pull request that fixes this issue by replacing it with the removeFormat command.

**Comment by JelteMX** [comment]
added PR #20 to release [3.3.0](https://github.com/mendix/Bootstrap-RTE/releases/tag/v3.3.0). That should fix the problem

**Comment by JelteMX** [comment]
Should be fixed in [latest version](https://github.com/mendix/Bootstrap-RTE/releases/tag/v4.0.0)
