### ISSUE TITLE
Can't add link at selected text in IE

### ISSUE THREAD

**Issue by jeroen-huizer-conclusion** [mendix/Bootstrap-RTE#24]
When opening the menu to add a link, the link-input box loses focus.
Clicking inside this box will not give it focus either.

I think this is a bug in the wysiwyg library, because the [demo](http://mindmup.github.io/bootstrap-wysiwyg/) shows the same behaviour.
It appears that the functionality to 'save' the selection triggers the blur event on the link-input box.

Any idea how to work around this?

Reproduced this issue in IE 11.0

**Comment by JelteMX** [comment]
It's connected to [this issue](https://github.com/steveathon/bootstrap-wysiwyg/issues/121). Unfortunately I can't fix that

**Comment by JelteMX** [comment]
I have taken the PR in the issue and applied it to the rewritten library here. Should be fixed in [latest version](https://github.com/mendix/Bootstrap-RTE/releases/tag/v4.0.0). I tested it on Edge/IE11
