### ISSUE TITLE
Can select only one emphasis when no text is selected in text area

### ISSUE THREAD

**Issue by melvingrootenboers** [mendix/Bootstrap-RTE#9]
1. Run the test project
2. Click on DataView - Editable
3. Click on 
![image](https://cloud.githubusercontent.com/assets/10810429/6708369/dd4866b4-cd6f-11e4-9688-58f165eb242c.png) -> Bold is selected
4. Click on 
![image](https://cloud.githubusercontent.com/assets/10810429/6708399/27abe212-cd70-11e4-8868-dca33397032c.png) -> Bold is deselected, Italic is selected

**Comment by JelteMX** [comment]
This is an issue with the library, not the widget itself
